language: cpp

matrix:
  include:
    - name: Test Ubuntu 16.04 + gcc-7 + codecov + sonarcloud
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
        sonarcloud:
          organization: "utilforever-github"
          token:
            secure: "JZM7ZH0E2p8CSU6sXxJ6Z0IujyHrqBHo4G+stlA/yWcLVjPsc5ub0ewYMloVj9DE4AlORahKLR8ZZeXT4i4pmI8SEQhzKmNjjYKG2wArqydyFoDzoP/cyTZFHhrO9cVL3/lkBkYt3ILTjuR7GgbU0utUFjhZpG/tJnMVkB1LenvM04ZN5DLr4k1H8OaXmFlsGN/llARmdyTmgMqInTu7qlD/uZIQOlwt1LudeWLCVlZMcbn/pJW0Oo26LU5fxgca/sEf5UeegjesQ/H8ZHZAaiKKIwQc6oJtptPtFNxXDqS68ReksfFv3v47JHUm4OiSFQXwSogw31UgAUXancYo4s9LzB/Y/cxlH0QhcUQ2jqmKRkjq1KmOIGJLeQT2JElSElrL7NxMM9NYneIALUvC7ef9RY5KVaYYV5zEaQ6qCCKVQayCPoqXrqAQ7ZKmNZ77vVX53ve7e03wVIWUeOjifDnHtK7Veg58bn5AwOpJmGS8Pd4cQXOehhniyx9iX0WSm/2/cyR6585TlR/v+V29uGW+jlwty8TJXdhYO/MjjhwsY1VKkGp+ySB5U6CpyB+nQSlprzqhYC/rt+RKctmsiPw4CAk3cLQqQYOV0+4yKr+lVKMQdRpZ1ZM3+9v6fPc15IVve7HtvZ1vN15nRuy+pWrEiu1m9PFWiggweOm1Y8c="
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
      script:
        - sh Scripts/travis_build_codecov.sh
    - name: Test Docker based on Ubuntu 18.04 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh
    - name: Test Docker based on Ubuntu 18.10 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.cosmic cosmic
    - name: Test Docker based on Ubuntu 19.04 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.disco disco
    - name: Test Docker based on Ubuntu 19.04 LTS + gcc-latest
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.disco.gcc-latest disco-gcc-latest
    - name: Test Docker based on Ubuntu 19.04 LTS + clang-latest
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.disco.clang-latest disco-clang-latest
    - name: Test OS X 10.14 + Xcode 10.2 + clang
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - sh Scripts/travis_build.sh
  before_install:
    - eval "${MATRIX_EVAL}"