version: 0.4 ({build})

skip_branch_with_pr: true

os:
  - Visual Studio 2017

platform:
  - x64

matrix:
  fast_finish: true  # Stop remaining jobs after a job failure

configuration:
  - Release

clone_folder: C:\RosettaStone

install:
  - git submodule update --init
  - ps: |
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017 Win64"
      $env:PYTHON = "36-x64"
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"

before_build:
  - md C:\RosettaStone\build
  - cd C:\RosettaStone\build
  - cmake .. -G "%CMAKE_GENERATOR%"

build:
  project: C:\RosettaStone\build\RosettaStone.sln
  parallel: true
  verbosity: normal

after_build:
  - C:\RosettaStone\build\bin\Release\UnitTests.exe